pyflakes fixes and CI
allisonkarlitskaya/systemd_ctypes pull request #13
Opened 2022-06-28 18:16 UTC by martinpitt

2022-06-28 22:01 UTC, allisonkarlitskaya requested changes

2022-06-29 04:19 UTC, martinpitt commented on example.py
> +    system.add_match("interface='org.freedesktop.DBus.Properties'", property_changed)
Sure, the return value is discarded, but the actual match/callback work without, I tested that. Presumably the reference to `property_changed` is stored internally, which keeps the slot alive. Anyway, I added a `del`.

2022-06-29 04:19 UTC, martinpitt commented on systemd_ctypes/__init__.py
> +__all__ = [ Bus, BusError, BusMessage, Event, EventLoopPolicy, PathWatch ]
That's what I started with, then ale reformatted it like this and I shrugged.. :grin: Done.

2022-06-29 04:21 UTC, martinpitt commented on .github/workflows/tests.yaml
> +              DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends python3-dbusmock libsystemd0 ${{ matrix.pyflakes }}
It's extra wasted time due to the download and install, but if you prefer, I can install it on Debian as well. Done.

2022-06-29 04:24 UTC, martinpitt commented on .github/workflows/tests.yaml
> +      - name: pyflakes
Heh, when I wrote this PR, tox was not in main yet. I was aware that you were going to drop test/run, which left me without a main entry point. Scanning installed files sounds wrong for static code checks -- if for no other reason that it breaks the file paths.

Agreed that there should be some single hook, I am just not sure where you would want to have it. In dbusmock I have [tests/test_code.py](https://github.com/martinpitt/python-dbusmock/blob/master/tests/test_code.py), i.e. "just another test". If you want that, I'm happy to do it that way.

2022-06-29 08:26 UTC, allisonkarlitskaya commented on .github/workflows/tests.yaml
> +      - name: pyflakes
I was thinking about that: it's actually a cool approach.

Would you invoke it by `import pyflake`?  Or `subprocess`?

2022-06-29 09:24 UTC, martinpitt commented on .github/workflows/tests.yaml
> +      - name: pyflakes
I didn't try running it via `import pyflakes`; so far I only ever ran it through `sys.interpreter -m pyflakes`, which works, and I didn't care enough to spend more time on that (I'm much more of a "good enough" developer wrt. build systems; I know you  are a lot more curiuos and a perfectionist there :grin: ).

2022-07-01 06:59 UTC, allisonkarlitskaya commented
I'm gonna drop the second commit from #14, land it, and then we can rebase this one on that and add the checks to the `tox` invocation.

2022-07-01 07:53 UTC, martinpitt commented
This needs to be re-done completely, and @allisonkarlitskaya said she wanted to look at that now. It's also much easier now with the tox runner, it can just be added there.

2022-07-01 07:53 UTC, closed without merging